- custom_typings/insight.d.ts
- package.json
- src/bin/typings.ts
- src/lib/compile.spec.ts
- src/lib/compile.ts
- src/typings.spec.ts
- src/typings.ts
- src/utils/config.ts
- src/utils/insight.ts
- tsconfig.json
Closes https://github.com/typings/cli/issues/26
> Add insight to CLI

- src/lib/dependencies.ts
> Resolve ambient dependencies on level always

- custom_typings/popsicle-cache.d.ts
- src/bin/typings.ts
- src/utils/config.ts
- src/utils/fs.ts
> Add the cache directory to CLI

- src/__test__/install-dependency-fixture/.gitignore
- src/__test__/install-fixture/custom_typings/ambient.d.ts
- src/__test__/install-fixture/custom_typings/definition.d.ts
- src/__test__/install-fixture/custom_typings/test.d.ts
- src/__test__/install-fixture/typings.json
- src/install.spec.ts
- src/install.ts
- src/interfaces/main.ts
- src/lib/compile.spec.ts
- src/lib/dependencies.spec.ts
- src/lib/dependencies.ts
- src/utils/fs.ts
* Adds tests for installing multiple dependencies
* Adds ambient installation to install everything test
* Always unlocks file writing with transform
Closes #58
> Support `ambientDevDependencies`

- README.md
- src/__test__/bundle/custom_typings/test.d.ts
- src/__test__/bundle/index.d.ts
- src/__test__/bundle/typings.json
- src/bin/typings-bundle.ts
- src/bin/typings.ts
- src/bundle.spec.ts
- src/bundle.ts
- src/install.spec.ts
- src/lib/compile.ts
- src/lib/dependencies.spec.ts
- src/lib/dependencies.ts
- src/typings.ts
- tsconfig.json
> Implement `typings bundle` command

- src/bundle.spec.ts
- src/install.spec.ts
- src/lib/compile.spec.ts
- src/lib/compile.ts
> Remove TypeScript typings formatter

- custom_typings/touch.d.ts
- package.json
- src/install.ts
- src/utils/fs.ts
- tsconfig.json
> Create `.d.ts` files when nothing is installed

- src/utils/cli.ts
Sorts each group of dependencies alphabetically when printing the result to screen.
> Sort dependencies on installation

- src/utils/fs.ts
Closes https://github.com/typings/typings/issues/81
> Append an EOL to JSON files

- src/utils/fs.ts
Improves the situation pointed out in #81 with Windows.
> Detect and use existing EOL when updating JSON

- src/utils/parse.spec.ts
- src/utils/parse.ts
> Resolves dependency paths relative to file

- src/utils/cli.ts
- src/utils/config.ts
> More verbose CLI error logging

- .gitignore
- .travis.yml
- README.md
- package.json
- src/install.spec.ts
- src/utils/debug.ts
- src/utils/fs.ts
- tsconfig.json
- typings.json
Having some trouble with HTTP in CI, debugging will really be helpful :+1:
> Add `debug` to project

- src/bundle.spec.ts
- src/lib/__test__/fixtures/compile/root.d.ts
- src/lib/compile.spec.ts
- src/lib/compile.ts
Closes https://github.com/typings/typings/issues/104
> Detect `export default` alongside other exports

- src/bin/typings-install.ts
Closes https://github.com/typings/typings/issues/112
> Prompt ambient only on install of non-ambient

- README.md
closes https://github.com/typings/typings/issues/151 :rose:
> :memo: document the initial setup for `main` vs. `browser`

- README.md
I update the contribution section to describe the steps needed.
Do you want to keep some of the note you originally have?
> Change contribution section to step by step guide

- package.json
Closes https://github.com/typings/typings/issues/172.
> Update to TypeScript@1.8.0

- README.md
> Fix typo in link on README.md

- src/utils/path.ts
Issue #207 - Add HTTP queryString support
> Issue #207 - Add HTTP queryString support

- src/bin/typings-install.ts
- src/lib/__test__/fixtures/compile-module-augmentation/import.d.ts
- src/lib/__test__/fixtures/compile-module-augmentation/index.d.ts
- src/lib/compile.spec.ts
- src/lib/compile.ts
From https://github.com/typings/typings/issues/119 /cc @andrew-w-ross
> Enable TypeScript 1.8+ module augmentation

- package.json
> Added missing module: xtend

- docs/tsd.md
As requested. Please merge if no one has any objections :rose:
> :memo: further tsd upgrade guidance

- README.md
- docs/examples.md
- docs/faq.md
Related to https://github.com/typings/typings/issues/360.
> Update docs and remove verbosity

- docs/examples.md
> Consistently adding a line after heading

- package.json
https://github.com/typings/typings/issues/250 build script works on windows (changed rm -rf with rimraf)
> https://github.com/typings/typings/issues/250 build script works on windows (changed rm -rf with rimraf)

- src/bin.ts
> Fix message

- src/support/cli.ts
> Add version to installing / root node

- docs/faq.md
Related to https://github.com/typings/typings/pull/400. @unional not sure it's a lot better, but instead of diving deep into details and specifics I tried to keep it more explicit and high level (hopefully something more link worthy in the FAQ).
> Write a little segment on types of typings

- docs/tsd.md
Related to https://github.com/typings/typings/pull/413.
> Link to module resolution docs from TSD docs

- README.md
As suggested by @johnnyreilly https://github.com/typings/typings/issues/436#issuecomment-209228116
> Add more examples to Quickstart

- README.md
Because, evidently, sources are confusing.
> Add a list of sources to README

- README.md
From https://github.com/typings/typings/issues/503#issuecomment-219508046.
> Correct examples in README quick start

- README.md
> Update README.md to clarify migration of typings.json

- README.md
I always find having an example to refer to invaluable and thought others might benefit.
> Update README.md to add example of dt install

- src/bin.ts
Closes https://github.com/typings/typings/issues/392.
> Resolve the users CWD argument

- README.md
Also killing the upgrade guide.
> Update README quickstart

- src/bin-install.ts
@blakeembrey As discussed on Gitter.
> Improve globaldependencies INFO message

- package.json
- src/bin-install.ts
- src/bin-list.ts
- src/bin.ts
- src/support/cli.ts
- typings.json
Closes https://github.com/typings/typings/issues/674.
> Enable `--unicode=false` option for archy
